# Generated by Django 3.2.6 on 2022-03-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='foto',
            field=models.ImageField(blank=True, upload_to='imgNino/', verbose_name='foto'),
        ),
    ]
