# Generated by Django 3.2.6 on 2022-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_alter_nino_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='foto',
            field=models.ImageField(blank=True, upload_to='ninos', verbose_name='foto'),
        ),
    ]
