# Generated by Django 3.2.6 on 2021-11-15 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruta', '0002_nino_adulto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='nombre_bitacora',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='tipo',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser'),
            preserve_default=False,
        ),
    ]
