# Generated by Django 3.2.6 on 2021-11-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_auto_20211115_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nino',
            name='cedula',
        ),
    ]
